services:
  db:
    image: postgres:15
    container_name: ia369_db
    environment:
      POSTGRES_DB: ia369_factoring
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    ports:
      - "5369:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
