spring.application.name=factoring-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/ia369_factoring
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080
